adminapp/urls.py
from django.contrib import admin
from django.urls import path
from adminapp import views

urlpatterns = [

    path('administration/',views.admin_login_view, name="admin_login_view"),
    path('admin_login/',views.admin_login, name="admin_login"),
    path('admin_logout/',views.admin_logout, name="admin_logout"),
    path('admin_user_view/',views.admin_user_view, name = "admin_user_view"),
    path('toggle_block_user/<int:user_id>/',views.toggle_block_user, name='toggle_block_user'),
    path('customer_search/',views.customer_search, name='customer_search'),

    path('admin/sales-report/', views.SalesReportView.as_view(), name='admin_sales_report'),
    path('sales-report/pdf/', views.SalesReportView.as_view(template_name='sales_report_pdf.html'), name='sales_report_pdf'),
    path('sales-report/download-pdf/', views.SalesReportView().download_pdf_report, name='download_pdf_report'),
    path('admin/ledger-book/', views.LedgerBookView.as_view(), name='ledger_book'),

    path('product_list/',views.product_list, name='product_list'),
    path('add_product/',views.add_product, name='add_product'),
    path('edit_product/<int:product_id>',views.edit_product, name='edit_product'),
    path('product_toggle_block/<int:product_id>/',views.product_toggle_block, name='product_toggle_block'),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),


    path('category_list/',views.category_list, name='category_list'),
    path('add_category/',views.add_category, name='add_category'),
    path('edit_category/<int:category_id>/',views.edit_category, name='edit_category'),


    path('category_toggle_block/<int:category_id>/',views.category_toggle_block, name='category_toggle_block'),
    path('categories/', views.category_search, name='category_search'),



    path('manage-variants/', views.manage_variants, name='manage_variants'),

    path('order_management/', views.admin_order_list, name='admin_order_list'),

    path('coupon-view', views.admin_coupon_view, name='coupon_view'),
    path('add-coupon/', views.add_coupon, name='add_coupon'),

    path('edit-coupon/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('delete-coupon/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),

    path('admin/manage-returns/', views.manage_returns, name='manage_returns'),
    path('admin/return-action/<int:return_id>/', views.return_action, name='return_action'),
    ]

hiker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('',include("user.urls")),
    path('',include("adminapp.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include("products.urls")),


    #path('accounts/', include('social_django.urls', namespace='social')),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

# + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views

urlpatterns = [

    path('',views.home, name="home"),
    path('login/',views.user_login, name="user_login"),
    path('user_login_view/',views.user_login_view, name="user_login_view"),
    path('logout/',views.user_logout, name="user_logout"),
    path('signup/',views.user_signup, name="user_signup"),
    path('validate_otp/', views.validate_otp, name='validate_otp'),
    path('resend_otp/', views.resend_otp, name='resend_otp'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_otp_validate/', views.password_otp_validate, name='password_otp_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),


    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_profile/edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_profile/edit_profile/profile_change_password/', views.profile_change_password, name='profile_change_password'),
    

    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('explore/', views.explore, name='explore'),

    path('wallet/', views.wallet, name='wallet'),
    path('coupon-list/', views.coupon_list, name='coupon_list'),

  

    ]

adminapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import Max,Aggregate

import os
from django.conf import settings
from django.utils import timezone
from datetime import timedelta,datetime
from django.core.exceptions import ValidationError
from django.db.models import Sum, F

# Create your models here
from decimal import Decimal


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, phone, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, last_name=last_name, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, first_name, last_name, phone, password, **extra_fields)


# models
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15, blank=True)

    addressOne = models.CharField(max_length=255, blank=True, null=True)
    street_address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=100, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    index = models.PositiveIntegerField(editable=False, null=True) 

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'phone']

    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        if self.pk is None:
            # Get the current highest index and add 1
            max_index = CustomUser.objects.aggregate(Max('index'))['index__max']
            self.index = (max_index or 0) + 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        current_index = self.index
        super().delete(*args, **kwargs)
        # Reindex remaining users
        users = CustomUser.objects.filter(index__gt=current_index).order_by('index')
        for user in users:
            user.index -= 1
            user.save()


#=====================Products--and--other--models====================#
class BaseModel(models.Model):
    added_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

class Category(BaseModel):
    name = models.CharField(max_length=100)
  

    def __str__(self):
        return self.name
    

class Variant(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def get_options(self):
        return self.options.all()
    
class VariantOption(models.Model):
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name='options')
    value = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.variant.name}: {self.value}"

class Image(models.Model):
    image = models.ImageField(upload_to='product_images/')
    alt_text = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Image {self.id}"
    
    @property
    def url(self):
        return self.image.url
    
    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super().delete(*args, **kwargs)

class Product(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    variant_option = models.ForeignKey(VariantOption, on_delete=models.CASCADE,null=True)
    images = models.ManyToManyField(Image, blank=True)
    is_active = models.BooleanField(default=True)
    index = models.PositiveIntegerField(editable=False, null=True)
    is_featured = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.name
    
    @property
    def offer_price(self):
        max_discount = self.get_max_discount_percentage()

        if max_discount > 0:
            discount_amount = (max_discount / Decimal('100')) * self.price
            offer_price = (self.price - discount_amount).quantize(Decimal('0.01'))
            return offer_price

        return self.price

    def get_product_offers(self):
        return self.offer_set.filter(discount_percentage__isnull=False).order_by('-discount_percentage')

    def get_category_offers(self):
        return CategoryOffer.objects.filter(category=self.category).order_by('-discount_percentage')

    def get_max_discount_percentage(self):
        product_offer = self.get_product_offers().first()
        category_offer = self.get_category_offers().first()

        product_discount = Decimal(product_offer.discount_percentage) if product_offer else Decimal('0')
        category_discount = Decimal(category_offer.discount_percentage) if category_offer else Decimal('0')

        return max(product_discount, category_discount)

    def get_discount_percentage(self):
        max_discount = self.get_max_discount_percentage()
        if max_discount > 0:
            return int(max_discount)
        return 0
        
    def save(self, *args, **kwargs):
        if self.pk is None:
            # Get the current highest index and add 1
            max_index = Product.objects.aggregate(models.Max('index'))['index__max']
            self.index = (max_index or 0) + 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        current_index = self.index
        super().delete(*args, **kwargs)
        # Reindex remaining products
        products = Product.objects.filter(index__gt=current_index).order_by('index')
        for product in products:
            product.index -= 1
            product.save()

    
class Offer(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True, blank=True)
    discount_percentage = models.IntegerField(null=True, blank=True)
    discount_name = models.CharField(max_length=255, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
   

    def __str__(self):
        return f"Offer {self.discount_percentage}%"
    
class CategoryOffer(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    discount_percentage = models.IntegerField(null=True, blank=True)    
    discount_name = models.CharField(max_length=255,null=True,blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.category.name} - ({self.discount_percentage}%)"

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return f"{self.product.name}: {self.rating} stars by {self.user.username}"
    

class Cart(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    items = models.ManyToManyField(Product, through='CartItem')
  


    def __str__(self):
        return f"Cart of {self.user.username}"
    
    

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f"{self.product.name} ({self.quantity}) in cart of {self.cart.user.username}"

class Wishlist(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    items = models.ManyToManyField(Product, through='WishlistItem')

    def __str__(self):         
        return f"Wishlist of {self.user.username}"

class WishlistItem(models.Model):
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.name} in wishlist of {self.wishlist.user.username}"

    


class OTP(models.Model):
    email = models.EmailField()
    otp = models.CharField(max_length=6)
    username = models.CharField(max_length=150,null=True)  # Add username field
    password = models.CharField(max_length=128,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def save(self, *args, **kwargs):
        self.expires_at = timezone.now() + timedelta(seconds=60)  # OTP valid for 5 minutes

adminapp/forms.py
from django import forms
from .models import Coupon

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'discount', 'valid_from', 'valid_to', 'active']
        widgets = {
            'code': forms.TextInput(attrs={'class': 'form-control'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control'}),
            'valid_from': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'valid_to': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['active'].widget.attrs['class'] = 'form-check-input'

adminapp/templates/admin_category_list.html
{% extends 'admin_base.html' %}
{% block title %}Category{% endblock title %}
{% block admin_content %}


  <div class='admin_content_search'>
    <div class="container mt-1  mb-0 ">
      <div class="banner_search">
          <div class="text-white search_text">Category</div>
          <div class="text-white btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Category +</div>
          <div class="search-container ">
            <form action="{% url 'category_search' %}" method="POST">{% csrf_token %}
                <input type="text" placeholder="Search..." name="search">
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
          </div>
      </div>
    </div>
  </div>


  <div class='category-table'>
    <div class="box m-5">
      <div class="table-responsive">
        <table class="table align-middle mb-0 table_bg py-5 text-dark">
          <thead class='text-light'>
            <tr class='text-dark table_row_head'>
              <th scope="col">ID</th>
              <th scope="col">Category</th>
              <th scope="col">Added</th>
              <th scope="col">Updated</th>
              <th scope="col">Offer</th>
              <th scope="col" class="ps-5">Action</th>
            </tr>
          </thead>      
          <!-- table-body-start -->
          <tbody>
            {% for category in categories %}
            <tr>
              <td data-label="ID">
                <p class="text-dark mb-0">{{ category.id }}</p>
              </td>
      
              <td data-label="Category">
                <p class="fw-bold text-dark mb-1">{{category.name}}</p>
              </td>
      
              <td data-label="Added">
                <p class="text-dark mb-0">{{category.added_date|date:"Y-m-d"}}</p>
              </td>
    
              <td data-label="Updated">
                <p class="text-dark mb-0">{{category.updated_date|date:"Y-m-d"}}</p>
              </td>
    
              <td data-label="Offer">
                {% with offer=category.categoryoffer_set.first %}
                  {% if offer %}
                    <p class="text-dark mb-0">{{offer.discount_percentage}}%</p>
                  {% else %}
                    <p class="text-dark mb-0">No offer</p>
                  {% endif %}
                {% endwith %}
              </td>
              
              <td data-label="Action">
                <div class="d-flex flex-wrap gap-2">
                  <button type="submit" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#edit_button_category-{{forloop.counter}}">
                    <i class="fas fa-edit"></i> Edit</button>
                  <form action="{% url 'category_toggle_block' category.id %}" method="POST">
                    {% csrf_token %}
                    {% if category.is_active %}
                      <button type="submit" class="btn btn-danger btn-sm">Block</button>
                    {% else %}
                      <button type="submit" class="btn btn-success btn-sm">Unblock</button>
                    {% endif %}
                  </form>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>



  {% comment %}----------- modal for adding CATEGORY --------------{% endcomment %}

  <div class="modal fade add_modal_product" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content p-5">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Add To Category</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'add_category' %}" method="POST" onsubmit="return validateForm(this)"> {% csrf_token %}
          <div class="modal-body">
            <div class="mb-3"> 
              <input type="text" class="form-control" name="category" placeholder="Category Name"  pattern="^[A-Za-z]+$">
            </div>
            <div class="mb-3"> 
              <input type="number" class="form-control" name="discount_percentage" placeholder="Discount Percentage"  min="0" max="100">
            </div>
            <div class="mb-3"> 
              <input type="text" class="form-control" name="discount_name" placeholder="Discount Name">
            </div>
            <div class="mb-3"> 
              <input type="date" class="form-control" name="start_date">
            </div>
            <div class="mb-3"> 
              <input type="date" class="form-control" name="end_date">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn add-product-btn">Add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% comment %}----------- modal for EDITING CATEGORY --------------{% endcomment %}

  {% for category in categories %}
    <div class="modal fade add_modal_product" id="edit_button_category-{{forloop.counter}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content p-5">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Edit Category</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{% url 'edit_category' category.id %}" method="POST" onsubmit="return validateForm(this)"> {% csrf_token %}
            <div class="modal-body">
              <div class="form-group pb-4">
                <label for="name" class="pb-2">Category Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ category.name }}" required>
              </div>
              {% with offer=category.categoryoffer_set.first %}
                <div class="form-group pb-4">
                  <label for="discount_percentage" class="pb-2">Discount Percentage</label>
                  <input type="number" class="form-control" id="discount_percentage" name="discount_percentage" value="{{ offer.discount_percentage|default:'' }}">
                </div>
                <div class="form-group pb-4">
                  <label for="discount_name" class="pb-2">Discount Name</label>
                  <input type="text" class="form-control" id="discount_name" name="discount_name" value="{{ offer.discount_name|default:'' }}">
                </div>
                <div class="form-group pb-4">
                  <label for="start_date" class="pb-2">Start Date</label>
                  <input type="date" class="form-control" id="start_date" name="start_date" value="{{ offer.start_date|date:'Y-m-d'|default:'' }}">
                </div>
                <div class="form-group pb-4">
                  <label for="end_date" class="pb-2">End Date</label>
                  <input type="date" class="form-control" id="end_date" name="end_date" value="{{ offer.end_date|date:'Y-m-d'|default:'' }}">
                </div>
              {% endwith %}
            </div>
            <div class="modal-footer pt-5">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn add-product-btn">Update</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endfor %}
  
<!-- ~~~~~~~~~SHOWING MESSAGES~~~~~~~~-->

  {% if messages %}
    <script>
        {% for message in messages %}
            Swal.fire({
                icon: '{{ message.tags }}',
                title: '{{ message.tags|title }}',
                text: '{{ message|safe }}',
            });
        {% endfor %}
    </script>
  {% endif %}

  <script>
    function validateForm(form) {
      var categoryName = form.querySelector('input[name="category"], input[name="name"]').value;
      var discountPercentage = form.querySelector('input[name="discount_percentage"]').value;
    
      // Validate category name (only letters, no spaces)
      if (!/^[A-Za-z]+$/.test(categoryName)) {
        
        Swal.fire({
          icon: 'error',
          title: 'OOPs..',
          text: 'Category name should contain only letters, no spaces or special characters.',
        });
        return false;
      }
    
      // Validate discount percentage (non-negative)
      if (discountPercentage !== "" && parseFloat(discountPercentage) < 0) {
        
        Swal.fire({
          icon: 'error',
          title: 'OOPs..',
          text: 'Discount percentage cannot be negative.',
        });
        return false;
      }
    
      return true;
    }
    </script>


{% endblock admin_content %}

adminapp/templates/admin_products_list.html
{% extends 'admin_base.html' %}
{% block title %}Product list{% endblock title %}

{% block admin_content %}
  <div class='admin_content_search'>
    <div class="container mt-1  mb-0">
      <div class="banner_search">
          <div class="text-white search_text">Products</div>
          <a href="{% url 'add_product' %}"><div class="text-white btn btn-outline-danger">Add Product +</div></a>
          <div class="search-container ">
            <form action="{% url 'customer_search' %}" method="POST">{% csrf_token %}
                <input type="text" placeholder="Search..." name="search">
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
          </div>
      </div>
    </div>
  </div>

  <div>
    <div class="box  m-5">
        <table class="table align-middle mb-0 table_bg py-5 text-dark">
            <thead class='text-light'>
                <tr class='text-dark text-center table_row_head'>
                <th scope="col">ID</th>
                <th scope="col">Product</th>
                <th scope="col"> Price</th>
                <th scope="col"> Stock</th>
                <th scope="col">Category</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
      
          <!-- table-body-start -->
          <tbody>
            {% for product in products %}
            <tr class="text-center">
              <td scope="row">
                <p class="text-dark mb-0">{{ product.index }}</p>
              </td>
      
              <td scope="row">
                  <p class="fw-bold text-dark mb-1">{{product.name}}</p>
              </td>
      
              <td scope="row">
                <p class="text-dark mb-0">{{product.price}}</p>
              </td>

              <td scope="row">
                <p class="text-dark mb-0">{{product.stock}}</p>
              </td>
      
              <td scope="row">
                <p class="text-dark mb-0">{{ product.category }}</p>
              </td>
              
              <td scope="row" class="d-flex justify-content-center">

                <a class="pe-2" href="{% url 'edit_product' product.id %}"><button type="button" class="btn btn-warning block">Edit</button></a>
            
                <form action="{% url 'product_toggle_block' product.id %}" method="POST" >
                  {% csrf_token %}
                  {% if product.is_active %}
                      <button type="submit" class="btn btn-danger block">Block</button>
                  {% else %}
                      <button type="submit" class="btn btn-success">Unblock</button>
                  {% endif %}
                </form>
               
              </td>
              
            </tr>
            {% endfor %}
      
          </tbody>
        </table>
      
      </div>
  </div>

  {% if messages %}
  <script>
      {% for message in messages %}
          Swal.fire({
              icon: '{{ message.tags }}',
              title: '{{ message.tags|title }}',
              text: '{{ message|safe }}',
          });
      {% endfor %}
  </script>
  {% endif %}

{% comment %} ------MODAL FOR ADDING PRODUCT -------{% endcomment %}

  

{% endblock admin_content %}

adminapp/templates/adminpage.html
{% extends 'admin_base.html' %}
{% block title %}admin home{% endblock title %}
{% block admin_content %}

{% endblock admin_content %}

adminapp/templates/ledger_book.html
{% extends 'admin_base.html' %}
{% load static %}

{% block title %}Ledger Book{% endblock title %}

{% block admin_content %}
<div class="ledger-book container mt-5">
    <h1>Ledger Book</h1>

    <div class="card mb-4">
        <div class="card-header">
            <h2>Summary</h2>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <p><strong>Total Debit:</strong> ${{ total_debit|floatformat:2 }}</p>
                </div>
                <div class="col-md-4">
                    <p><strong>Total Credit:</strong> ${{ total_credit|floatformat:2 }}</p>
                </div>
                <div class="col-md-4">
                    <p><strong>Balance:</strong> ${{ balance|floatformat:2 }}</p>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.date|date:"Y-m-d H:i" }}</td>
                <td>{{ item.description }}</td>
                <td>${{ item.amount|floatformat:2 }}</td>
                <td>{{ item.type|title }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock admin_content %}